name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install OS Packages
      uses: mstksg/get-package@v1
      with:
        apt-get: libsqlite3-dev ruby-rspec-core
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test with rspec
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        rake db:migrate
        rspec tests
      env:
        CI: true
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        BENCH_DB_PATH: sqlite:/tmp/data.db
        BUILDKITE_API_TOKEN: fake_api_token
